#!/bin/bash

echo "🎧 Twitter Spaces Audio Setup Script"
echo "======================================"
echo ""

# Install BlackHole
echo "📦 Installing BlackHole virtual audio device..."
echo "   (You'll need to enter your password)"
echo ""

brew install blackhole-2ch

if [ $? -eq 0 ]; then
    echo ""
    echo "✅ BlackHole installed!"
    echo ""
    echo "⚠️  IMPORTANT: You must REBOOT your Mac for BlackHole to work!"
    echo ""
    echo "After reboot:"
    echo "  1. Open 'Audio MIDI Setup' app"
    echo "  2. Follow the configuration steps below"
    echo ""
else
    echo ""
    echo "❌ Installation failed or requires password"
    echo ""
    echo "Manual installation:"
    echo "  1. Go to: https://existential.audio/blackhole/"
    echo "  2. Download BlackHole 2ch"
    echo "  3. Install the .pkg file"
    echo "  4. Reboot your Mac"
    echo ""
fi

echo "======================================"
echo "📋 CONFIGURATION STEPS (After Reboot)"
echo "======================================"
echo ""
echo "Step 1: Open 'Audio MIDI Setup'"
echo "  • Applications → Utilities → Audio MIDI Setup"
echo ""
echo "Step 2: Create Multi-Output Device"
echo "  • Click '+' (bottom left)"
echo "  • Choose 'Create Multi-Output Device'"
echo "  • Name it: 'Spaces Output'"
echo "  • Check BOTH:"
echo "    ✅ BlackHole 2ch"
echo "    ✅ MacBook Pro Speakers (or your speakers)"
echo ""
echo "Step 3: Create Aggregate Device"
echo "  • Click '+' again"
echo "  • Choose 'Create Aggregate Device'"
echo "  • Name it: 'Spaces Input'"
echo "  • Check BOTH:"
echo "    ✅ BlackHole 2ch"
echo "    ✅ MacBook Pro Microphone (or your mic)"
echo ""
echo "Step 4: Set as System Default"
echo "  • System Settings → Sound"
echo "  • Output: Select 'Spaces Output'"
echo "  • Input: Select 'Spaces Input'"
echo ""
echo "======================================"
echo "🧪 TESTING"
echo "======================================"
echo ""
echo "After setup, run:"
echo "  python3 test_blackhole.py"
echo ""
echo "This will verify BlackHole is working!"
echo ""


